import { createHmac } from 'node:crypto';

/**
 * BYO ("customer S3") provisioning artifacts. The CloudFormation template here
 * is the canonical one-command setup for a partner's AWS account: private
 * encrypted bucket + a least-privilege cross-account role Effigent can assume.
 * `infra/aws/` in the repo carries the same template (plus a Terraform module)
 * for partners who want raw files; keep them in sync.
 */

/**
 * Deterministic per-org external id for the cross-account trust condition.
 * Derived (HMAC) rather than stored so it exists before any config is saved and
 * survives config resets. Set EFFIGENT_EXTERNAL_ID_SECRET in the deployment —
 * the fallback keeps dev working but is not a secret.
 */
export function externalIdFor(tenantId: string): string {
  const secret = process.env.EFFIGENT_EXTERNAL_ID_SECRET || 'effigent-dev-external-id';
  return `eff-ext-${createHmac('sha256', secret).update(tenantId).digest('hex').slice(0, 24)}`;
}

/** The AWS account Effigent's collector runs as (partners trust this account). */
export function effigentAccountId(): string | null {
  return process.env.EFFIGENT_AWS_ACCOUNT_ID || null;
}

/**
 * CloudFormation template for the partner's account, with this org's external
 * id and Effigent's account id baked in as parameter defaults — so
 * `aws cloudformation deploy` needs no hand-typed parameters.
 */
export function renderCfnTemplate(opts: { externalId: string; effigentAccountId: string }): string {
  return `AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Effigent BYO run storage: a private, encrypted S3 bucket in YOUR account plus
  a least-privilege cross-account role (PutObject/GetObject on this one bucket
  only). Delete the stack (or the role) to revoke Effigent's access instantly.

Parameters:
  EffigentAccountId:
    Type: String
    Default: '${opts.effigentAccountId}'
    Description: Effigent's AWS account id (the only principal allowed to assume the role).
    AllowedPattern: '^[0-9]{12}$'
  ExternalId:
    Type: String
    Default: '${opts.externalId}'
    Description: Per-workspace external id (generated by Effigent) required on every AssumeRole.
    MinLength: 8
  BucketName:
    Type: String
    Default: ''
    Description: Optional bucket name. Leave empty to let AWS generate one.
  KmsKeyArn:
    Type: String
    Default: ''
    Description: Optional CMK ARN. Leave empty for SSE-S3 (AES256).

Conditions:
  HasBucketName: !Not [!Equals [!Ref BucketName, '']]
  HasKms: !Not [!Equals [!Ref KmsKeyArn, '']]

Resources:
  RunBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If [HasBucketName, !Ref BucketName, !Ref 'AWS::NoValue']
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault: !If
              - HasKms
              - SSEAlgorithm: 'aws:kms'
                KMSMasterKeyID: !Ref KmsKeyArn
              - SSEAlgorithm: AES256
            BucketKeyEnabled: true

  EffigentAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'effigent-run-storage-\${AWS::StackName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::\${EffigentAccountId}:root'
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalId
      Policies:
        - PolicyName: effigent-run-blobs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: EffigentRunBlobs
                Effect: Allow
                Action: ['s3:PutObject', 's3:GetObject']
                Resource: !Sub '\${RunBucket.Arn}/*'
              - !If
                - HasKms
                - Sid: EffigentRunBlobsKms
                  Effect: Allow
                  Action: ['kms:GenerateDataKey', 'kms:Decrypt']
                  Resource: !Ref KmsKeyArn
                - !Ref 'AWS::NoValue'

Outputs:
  Bucket:
    Description: Enter this as "Bucket" in the Effigent Storage settings.
    Value: !Ref RunBucket
  Region:
    Description: Enter this as "Region".
    Value: !Ref 'AWS::Region'
  RoleArn:
    Description: Enter this as "Role ARN".
    Value: !GetAtt EffigentAccessRole.Arn
  KmsKeyArn:
    Description: Enter this as "KMS key ARN" (empty = SSE-S3).
    Value: !Ref KmsKeyArn
`;
}
