# Effigent BYO run storage — Terraform module.
# Creates a private encrypted bucket in YOUR account plus a least-privilege
# cross-account role Effigent assumes (PutObject/GetObject on this one bucket
# only). `terraform destroy` (or deleting the role) revokes access instantly.
#
# Usage:
#   module "effigent_storage" {
#     source              = "./infra/aws/terraform"
#     effigent_account_id = "<12 digits — ask Effigent, or see the dashboard Storage view>"
#     external_id         = "<eff-ext-… — shown in the dashboard Storage view>"
#     # bucket_name       = "my-effigent-runs"   (optional)
#     # kms_key_arn       = aws_kms_key.runs.arn (optional)
#   }
# Then enter the module outputs in the Effigent dashboard Storage settings.
#
# Keep behavior in sync with infra/aws/effigent-byo-storage.yaml.

variable "effigent_account_id" {
  type        = string
  description = "Effigent's AWS account id (the only principal allowed to assume the role)."
  validation {
    condition     = can(regex("^[0-9]{12}$", var.effigent_account_id))
    error_message = "Must be a 12-digit AWS account id."
  }
}

variable "external_id" {
  type        = string
  description = "Per-workspace external id (generated by Effigent) required on every AssumeRole."
}

variable "bucket_name" {
  type        = string
  default     = null
  description = "Optional bucket name; null lets AWS generate one."
}

variable "kms_key_arn" {
  type        = string
  default     = null
  description = "Optional CMK ARN; null uses SSE-S3 (AES256)."
}

variable "role_name" {
  type        = string
  default     = "effigent-run-storage"
  description = "Name of the cross-account role Effigent assumes."
}

resource "aws_s3_bucket" "runs" {
  bucket = var.bucket_name
}

resource "aws_s3_bucket_public_access_block" "runs" {
  bucket                  = aws_s3_bucket.runs.id
  block_public_acls       = true
  ignore_public_acls      = true
  block_public_policy     = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "runs" {
  bucket = aws_s3_bucket.runs.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm     = var.kms_key_arn != null ? "aws:kms" : "AES256"
      kms_master_key_id = var.kms_key_arn
    }
    bucket_key_enabled = true
  }
}

data "aws_iam_policy_document" "trust" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]
    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::${var.effigent_account_id}:root"]
    }
    condition {
      test     = "StringEquals"
      variable = "sts:ExternalId"
      values   = [var.external_id]
    }
  }
}

data "aws_iam_policy_document" "run_blobs" {
  statement {
    sid       = "EffigentRunBlobs"
    effect    = "Allow"
    actions   = ["s3:PutObject", "s3:GetObject"]
    resources = ["${aws_s3_bucket.runs.arn}/*"]
  }

  dynamic "statement" {
    for_each = var.kms_key_arn != null ? [1] : []
    content {
      sid       = "EffigentRunBlobsKms"
      effect    = "Allow"
      actions   = ["kms:GenerateDataKey", "kms:Decrypt"]
      resources = [var.kms_key_arn]
    }
  }
}

resource "aws_iam_role" "effigent" {
  name               = var.role_name
  assume_role_policy = data.aws_iam_policy_document.trust.json
}

resource "aws_iam_role_policy" "effigent" {
  name   = "effigent-run-blobs"
  role   = aws_iam_role.effigent.id
  policy = data.aws_iam_policy_document.run_blobs.json
}

data "aws_region" "current" {}

output "bucket" {
  value       = aws_s3_bucket.runs.id
  description = "Enter this as \"Bucket\" in the Effigent Storage settings."
}

output "region" {
  value       = data.aws_region.current.region
  description = "Enter this as \"Region\"."
}

output "role_arn" {
  value       = aws_iam_role.effigent.arn
  description = "Enter this as \"Role ARN\"."
}
